/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'Roboto', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Arial', 'sans-serif'],
      },
      colors: {
        brand: {
          brown: '#33281f',
          'brown-dark': '#1a140f',
          'brown-light': '#8B7B6B',
          'brown-lighter': '#D4C7B8',
          'brown-warm': '#5D4E37',
          chocolate: '#3E2723',
          charcoal: '#2D2D2D',
          orange: '#e38347',
          'orange-dark': '#d45b19',
          'orange-light': '#F5B88A',
          'orange-hover': '#ffc04a',
          'orange-muted': '#E89F71',
          terracotta: '#D4826C',
          'terracotta-dark': '#C67259',
          'terracotta-light': '#E5A58D',
          cyan: '#bbe8f1',
          'cyan-light': '#d4f3f8',
          'cyan-hover': '#d0ecf3',
          cream: '#fcf8f5',
          'cream-dark': '#FAF4EE',
          'off-white': '#FAFAFA',
          beige: '#F5F5DC',
          'beige-light': '#FAFAF0',
          tan: '#EBE4D8',
          'tan-light': '#F5F0E8',
          gold: '#d6a81e',
          green: '#00d495',
          'green-light': '#99f3d9',
          navy: '#2C3E50',
          gray: {
            1: '#736b65',
            2: '#ccbeb3',
            3: '#e5ded8',
            4: '#f2ede9',
            5: '#fcf8f5',
            6: '#ffffff',
          },
        },
      },
      boxShadow: {
        'soft': '0 2px 8px rgba(93, 78, 55, 0.08)',
        'soft-md': '0 4px 12px rgba(93, 78, 55, 0.1)',
        'soft-lg': '0 8px 20px rgba(93, 78, 55, 0.12)',
      },
      spacing: {
        'touch': '44px',
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      minHeight: {
        'touch': '44px',
      },
      minWidth: {
        'touch': '44px',
      },
    },
  },
  plugins: [],
};
